FROM node:22-alpine
WORKDIR /app

ARG PUBLIC_WALLET_CONNECT_PROJECT_ID
ARG PUBLIC_NETWORK

ENV PUBLIC_WALLET_CONNECT_PROJECT_ID ${PUBLIC_WALLET_CONNECT_PROJECT_ID}
ENV PUBLIC_NETWORK ${PUBLIC_NETWORK}

COPY package*.json .
RUN npm i --force
COPY . .

RUN npm run build

EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build" ]
