FROM oven/bun:1.3.1
WORKDIR /app

ARG PUBLIC_WALLET_CONNECT_PROJECT_ID
ARG PUBLIC_NETWORK

ENV PUBLIC_WALLET_CONNECT_PROJECT_ID=${PUBLIC_WALLET_CONNECT_PROJECT_ID}
ENV PUBLIC_NETWORK=${PUBLIC_NETWORK}

COPY . .
RUN bun i

RUN bun run build

EXPOSE 3000
ENV NODE_ENV=production
CMD [ "bun", "run", "build/index.js" ]
